### PR TITLE
Feature/events

### PR DESCRIPTION
**Pull request by Gnwin**
## Math Magicians: Events

In this milestone, the logic of the application was built without without any errors. All requirements for this milestone have been met according to this document:

https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_events.md

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi guys, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 


## Required Changes ♻️
   - [x] You have used a wrong folder structure for a React project. you have placed react components and tests inside assets directory which is not correct because react components or tests for those components are not of type asset(in react, assets can be pictures, CSS or SCSS files, fonts etc), so they should be on src directory. Kindly fix it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Gnwin** [comment]
Thanks @rukundoeric

**Review by bini-i — APPROVED** [review]
# Status: Approved :heavy_check_mark:          
### Hello @Gnwin  :wave: 

**Congratulations**, your project meets all the requirements and it is **approved** :tada:.

#### To highlight
- Good use of git workflow
- UI well implemented
- very good binding click event after componentDidMount making your render DRY.

#### If you have any questions feel free to ask within the PR thread.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Comment by Gnwin** [comment]
Thanks @bini-i.

**Pull request merged**
